# Generated by Django 6.0.7 on 2026-08-01 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_checked_in_registration_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ticket_qr',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/qr/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ticket_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
