# Generated by Django 6.0.7 on 2026-08-01 12:37

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
        ('registrations', '0003_registration_ticket_qr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='checked_in',
            field=models.BooleanField(default=False, help_text='Whether attendee has entered the event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ticket_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique QR ticket identifier', unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ticket_qr',
            field=models.ImageField(blank=True, help_text='Generated QR code for this ticket', null=True, upload_to='tickets/qr/'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['ticket_code'], name='registratio_ticket__241216_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['attendee', 'status'], name='registratio_attende_41b206_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'status'], name='registratio_event_i_246b4a_idx'),
        ),
    ]
